[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sandbox-pinocchio-parallel-robots"
version = "0.0.1"
dependencies = [
  "pin"
]

[tool.setuptools]
packages = [
  "sandbox_pinocchio_parallel_robots"
]
